export const quirkyGreetings = [
  'Hey there ',
  'Hi ',
  'Hello ',
  'Greetings ',
  'Salutations ',
  'Yo ',
  'What up ',
  'Howdy ',
  'What\'s cookin ',
  'Aloha ',
  'Bonjour ',
  'Ciao ',
  'Hola ',
  'Shalom ',
  'Namaste ',
  'Salaam ',
  'Konnichiwa ',
  'G\'day ',
  'Guten tag ',
  'Greetings Earthling ',
]